const actions = {
    SINGLE: 'SINGLE',
    DOUBLE: 'DOUBLE',
    TRIPLE: 'TRIPLE',
    HOME_RUN: 'HOME_RUN',
    WALK: 'WALK',
    ADVANCE_ALL_RUNNERS: 'ADVANCE_ALL_RUNNERS',
    ADVANCE_AVAILABLE_BASES: 'ADVANCE_AVAILABLE_BASES'
}

export default actions